# Generated by Django 3.0.6 on 2020-07-19 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_order_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, choices=[('Indoor', 'Indoor'), ('Out of door', 'Out of door')], null=True),
        ),
    ]
